// Code generated by ent, DO NOT EDIT.

package fcirclestatistic

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldID, id))
}

// FriendsNum applies equality check predicate on the "friends_num" field. It's identical to FriendsNumEQ.
func FriendsNum(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldFriendsNum, v))
}

// ActiveNum applies equality check predicate on the "active_num" field. It's identical to ActiveNumEQ.
func ActiveNum(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldActiveNum, v))
}

// ErrorNum applies equality check predicate on the "error_num" field. It's identical to ErrorNumEQ.
func ErrorNum(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldErrorNum, v))
}

// ArticleNum applies equality check predicate on the "article_num" field. It's identical to ArticleNumEQ.
func ArticleNum(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldArticleNum, v))
}

// LastUpdatedTime applies equality check predicate on the "last_updated_time" field. It's identical to LastUpdatedTimeEQ.
func LastUpdatedTime(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldLastUpdatedTime, v))
}

// FriendsNumEQ applies the EQ predicate on the "friends_num" field.
func FriendsNumEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldFriendsNum, v))
}

// FriendsNumNEQ applies the NEQ predicate on the "friends_num" field.
func FriendsNumNEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldFriendsNum, v))
}

// FriendsNumIn applies the In predicate on the "friends_num" field.
func FriendsNumIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldFriendsNum, vs...))
}

// FriendsNumNotIn applies the NotIn predicate on the "friends_num" field.
func FriendsNumNotIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldFriendsNum, vs...))
}

// FriendsNumGT applies the GT predicate on the "friends_num" field.
func FriendsNumGT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldFriendsNum, v))
}

// FriendsNumGTE applies the GTE predicate on the "friends_num" field.
func FriendsNumGTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldFriendsNum, v))
}

// FriendsNumLT applies the LT predicate on the "friends_num" field.
func FriendsNumLT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldFriendsNum, v))
}

// FriendsNumLTE applies the LTE predicate on the "friends_num" field.
func FriendsNumLTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldFriendsNum, v))
}

// ActiveNumEQ applies the EQ predicate on the "active_num" field.
func ActiveNumEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldActiveNum, v))
}

// ActiveNumNEQ applies the NEQ predicate on the "active_num" field.
func ActiveNumNEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldActiveNum, v))
}

// ActiveNumIn applies the In predicate on the "active_num" field.
func ActiveNumIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldActiveNum, vs...))
}

// ActiveNumNotIn applies the NotIn predicate on the "active_num" field.
func ActiveNumNotIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldActiveNum, vs...))
}

// ActiveNumGT applies the GT predicate on the "active_num" field.
func ActiveNumGT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldActiveNum, v))
}

// ActiveNumGTE applies the GTE predicate on the "active_num" field.
func ActiveNumGTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldActiveNum, v))
}

// ActiveNumLT applies the LT predicate on the "active_num" field.
func ActiveNumLT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldActiveNum, v))
}

// ActiveNumLTE applies the LTE predicate on the "active_num" field.
func ActiveNumLTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldActiveNum, v))
}

// ErrorNumEQ applies the EQ predicate on the "error_num" field.
func ErrorNumEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldErrorNum, v))
}

// ErrorNumNEQ applies the NEQ predicate on the "error_num" field.
func ErrorNumNEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldErrorNum, v))
}

// ErrorNumIn applies the In predicate on the "error_num" field.
func ErrorNumIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldErrorNum, vs...))
}

// ErrorNumNotIn applies the NotIn predicate on the "error_num" field.
func ErrorNumNotIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldErrorNum, vs...))
}

// ErrorNumGT applies the GT predicate on the "error_num" field.
func ErrorNumGT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldErrorNum, v))
}

// ErrorNumGTE applies the GTE predicate on the "error_num" field.
func ErrorNumGTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldErrorNum, v))
}

// ErrorNumLT applies the LT predicate on the "error_num" field.
func ErrorNumLT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldErrorNum, v))
}

// ErrorNumLTE applies the LTE predicate on the "error_num" field.
func ErrorNumLTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldErrorNum, v))
}

// ArticleNumEQ applies the EQ predicate on the "article_num" field.
func ArticleNumEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldArticleNum, v))
}

// ArticleNumNEQ applies the NEQ predicate on the "article_num" field.
func ArticleNumNEQ(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldArticleNum, v))
}

// ArticleNumIn applies the In predicate on the "article_num" field.
func ArticleNumIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldArticleNum, vs...))
}

// ArticleNumNotIn applies the NotIn predicate on the "article_num" field.
func ArticleNumNotIn(vs ...int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldArticleNum, vs...))
}

// ArticleNumGT applies the GT predicate on the "article_num" field.
func ArticleNumGT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldArticleNum, v))
}

// ArticleNumGTE applies the GTE predicate on the "article_num" field.
func ArticleNumGTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldArticleNum, v))
}

// ArticleNumLT applies the LT predicate on the "article_num" field.
func ArticleNumLT(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldArticleNum, v))
}

// ArticleNumLTE applies the LTE predicate on the "article_num" field.
func ArticleNumLTE(v int) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldArticleNum, v))
}

// LastUpdatedTimeEQ applies the EQ predicate on the "last_updated_time" field.
func LastUpdatedTimeEQ(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldEQ(FieldLastUpdatedTime, v))
}

// LastUpdatedTimeNEQ applies the NEQ predicate on the "last_updated_time" field.
func LastUpdatedTimeNEQ(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNEQ(FieldLastUpdatedTime, v))
}

// LastUpdatedTimeIn applies the In predicate on the "last_updated_time" field.
func LastUpdatedTimeIn(vs ...time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldIn(FieldLastUpdatedTime, vs...))
}

// LastUpdatedTimeNotIn applies the NotIn predicate on the "last_updated_time" field.
func LastUpdatedTimeNotIn(vs ...time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldNotIn(FieldLastUpdatedTime, vs...))
}

// LastUpdatedTimeGT applies the GT predicate on the "last_updated_time" field.
func LastUpdatedTimeGT(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGT(FieldLastUpdatedTime, v))
}

// LastUpdatedTimeGTE applies the GTE predicate on the "last_updated_time" field.
func LastUpdatedTimeGTE(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldGTE(FieldLastUpdatedTime, v))
}

// LastUpdatedTimeLT applies the LT predicate on the "last_updated_time" field.
func LastUpdatedTimeLT(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLT(FieldLastUpdatedTime, v))
}

// LastUpdatedTimeLTE applies the LTE predicate on the "last_updated_time" field.
func LastUpdatedTimeLTE(v time.Time) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.FieldLTE(FieldLastUpdatedTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FCircleStatistic) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FCircleStatistic) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FCircleStatistic) predicate.FCircleStatistic {
	return predicate.FCircleStatistic(sql.NotPredicates(p))
}
