// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/albumcategory"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// AlbumCategoryDelete is the builder for deleting a AlbumCategory entity.
type AlbumCategoryDelete struct {
	config
	hooks    []Hook
	mutation *AlbumCategoryMutation
}

// Where appends a list predicates to the AlbumCategoryDelete builder.
func (acd *AlbumCategoryDelete) Where(ps ...predicate.AlbumCategory) *AlbumCategoryDelete {
	acd.mutation.Where(ps...)
	return acd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (acd *AlbumCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, acd.sqlExec, acd.mutation, acd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (acd *AlbumCategoryDelete) ExecX(ctx context.Context) int {
	n, err := acd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (acd *AlbumCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(albumcategory.Table, sqlgraph.NewFieldSpec(albumcategory.FieldID, field.TypeUint))
	if ps := acd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, acd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	acd.mutation.done = true
	return affected, err
}

// AlbumCategoryDeleteOne is the builder for deleting a single AlbumCategory entity.
type AlbumCategoryDeleteOne struct {
	acd *AlbumCategoryDelete
}

// Where appends a list predicates to the AlbumCategoryDelete builder.
func (acdo *AlbumCategoryDeleteOne) Where(ps ...predicate.AlbumCategory) *AlbumCategoryDeleteOne {
	acdo.acd.mutation.Where(ps...)
	return acdo
}

// Exec executes the deletion query.
func (acdo *AlbumCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := acdo.acd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{albumcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (acdo *AlbumCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := acdo.Exec(ctx); err != nil {
		panic(err)
	}
}
