// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anzhiyu-c/anheyu-app/ent/essay"
)

// 随笔记录表
type Essay struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID uint `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 随笔内容
	Content string `json:"content,omitempty"`
	// 随笔日期
	Date time.Time `json:"date,omitempty"`
	// 随笔图片列表(JSON格式字符串)
	Images string `json:"images,omitempty"`
	// 随笔链接
	Link         string `json:"link,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Essay) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case essay.FieldID:
			values[i] = new(sql.NullInt64)
		case essay.FieldContent, essay.FieldImages, essay.FieldLink:
			values[i] = new(sql.NullString)
		case essay.FieldDeletedAt, essay.FieldCreatedAt, essay.FieldUpdatedAt, essay.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Essay fields.
func (e *Essay) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case essay.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = uint(value.Int64)
		case essay.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				e.DeletedAt = new(time.Time)
				*e.DeletedAt = value.Time
			}
		case essay.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case essay.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		case essay.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				e.Content = value.String
			}
		case essay.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				e.Date = value.Time
			}
		case essay.FieldImages:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field images", values[i])
			} else if value.Valid {
				e.Images = value.String
			}
		case essay.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				e.Link = value.String
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Essay.
// This includes values selected through modifiers, order, etc.
func (e *Essay) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// Update returns a builder for updating this Essay.
// Note that you need to call Essay.Unwrap() before calling this method if this Essay
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Essay) Update() *EssayUpdateOne {
	return NewEssayClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Essay entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Essay) Unwrap() *Essay {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Essay is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Essay) String() string {
	var builder strings.Builder
	builder.WriteString("Essay(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	if v := e.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(e.Content)
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(e.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("images=")
	builder.WriteString(e.Images)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(e.Link)
	builder.WriteByte(')')
	return builder.String()
}

// Essays is a parsable slice of Essay.
type Essays []*Essay
