// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/essay"
)

// EssayCreate is the builder for creating a Essay entity.
type EssayCreate struct {
	config
	mutation *EssayMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (ec *EssayCreate) SetDeletedAt(t time.Time) *EssayCreate {
	ec.mutation.SetDeletedAt(t)
	return ec
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ec *EssayCreate) SetNillableDeletedAt(t *time.Time) *EssayCreate {
	if t != nil {
		ec.SetDeletedAt(*t)
	}
	return ec
}

// SetCreatedAt sets the "created_at" field.
func (ec *EssayCreate) SetCreatedAt(t time.Time) *EssayCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *EssayCreate) SetNillableCreatedAt(t *time.Time) *EssayCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetUpdatedAt sets the "updated_at" field.
func (ec *EssayCreate) SetUpdatedAt(t time.Time) *EssayCreate {
	ec.mutation.SetUpdatedAt(t)
	return ec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ec *EssayCreate) SetNillableUpdatedAt(t *time.Time) *EssayCreate {
	if t != nil {
		ec.SetUpdatedAt(*t)
	}
	return ec
}

// SetContent sets the "content" field.
func (ec *EssayCreate) SetContent(s string) *EssayCreate {
	ec.mutation.SetContent(s)
	return ec
}

// SetDate sets the "date" field.
func (ec *EssayCreate) SetDate(t time.Time) *EssayCreate {
	ec.mutation.SetDate(t)
	return ec
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ec *EssayCreate) SetNillableDate(t *time.Time) *EssayCreate {
	if t != nil {
		ec.SetDate(*t)
	}
	return ec
}

// SetImages sets the "images" field.
func (ec *EssayCreate) SetImages(s string) *EssayCreate {
	ec.mutation.SetImages(s)
	return ec
}

// SetNillableImages sets the "images" field if the given value is not nil.
func (ec *EssayCreate) SetNillableImages(s *string) *EssayCreate {
	if s != nil {
		ec.SetImages(*s)
	}
	return ec
}

// SetLink sets the "link" field.
func (ec *EssayCreate) SetLink(s string) *EssayCreate {
	ec.mutation.SetLink(s)
	return ec
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (ec *EssayCreate) SetNillableLink(s *string) *EssayCreate {
	if s != nil {
		ec.SetLink(*s)
	}
	return ec
}

// SetID sets the "id" field.
func (ec *EssayCreate) SetID(u uint) *EssayCreate {
	ec.mutation.SetID(u)
	return ec
}

// Mutation returns the EssayMutation object of the builder.
func (ec *EssayCreate) Mutation() *EssayMutation {
	return ec.mutation
}

// Save creates the Essay in the database.
func (ec *EssayCreate) Save(ctx context.Context) (*Essay, error) {
	if err := ec.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EssayCreate) SaveX(ctx context.Context) *Essay {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EssayCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EssayCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EssayCreate) defaults() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		if essay.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized essay.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := essay.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		if essay.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized essay.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := essay.DefaultUpdatedAt()
		ec.mutation.SetUpdatedAt(v)
	}
	if _, ok := ec.mutation.Date(); !ok {
		if essay.DefaultDate == nil {
			return fmt.Errorf("ent: uninitialized essay.DefaultDate (forgotten import ent/runtime?)")
		}
		v := essay.DefaultDate()
		ec.mutation.SetDate(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ec *EssayCreate) check() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Essay.created_at"`)}
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Essay.updated_at"`)}
	}
	if _, ok := ec.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Essay.content"`)}
	}
	if _, ok := ec.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Essay.date"`)}
	}
	return nil
}

func (ec *EssayCreate) sqlSave(ctx context.Context) (*Essay, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EssayCreate) createSpec() (*Essay, *sqlgraph.CreateSpec) {
	var (
		_node = &Essay{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(essay.Table, sqlgraph.NewFieldSpec(essay.FieldID, field.TypeUint))
	)
	_spec.OnConflict = ec.conflict
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ec.mutation.DeletedAt(); ok {
		_spec.SetField(essay.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(essay.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.SetField(essay.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.Content(); ok {
		_spec.SetField(essay.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := ec.mutation.Date(); ok {
		_spec.SetField(essay.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := ec.mutation.Images(); ok {
		_spec.SetField(essay.FieldImages, field.TypeString, value)
		_node.Images = value
	}
	if value, ok := ec.mutation.Link(); ok {
		_spec.SetField(essay.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Essay.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EssayUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (ec *EssayCreate) OnConflict(opts ...sql.ConflictOption) *EssayUpsertOne {
	ec.conflict = opts
	return &EssayUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Essay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ec *EssayCreate) OnConflictColumns(columns ...string) *EssayUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &EssayUpsertOne{
		create: ec,
	}
}

type (
	// EssayUpsertOne is the builder for "upsert"-ing
	//  one Essay node.
	EssayUpsertOne struct {
		create *EssayCreate
	}

	// EssayUpsert is the "OnConflict" setter.
	EssayUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *EssayUpsert) SetDeletedAt(v time.Time) *EssayUpsert {
	u.Set(essay.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EssayUpsert) UpdateDeletedAt() *EssayUpsert {
	u.SetExcluded(essay.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EssayUpsert) ClearDeletedAt() *EssayUpsert {
	u.SetNull(essay.FieldDeletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EssayUpsert) SetUpdatedAt(v time.Time) *EssayUpsert {
	u.Set(essay.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EssayUpsert) UpdateUpdatedAt() *EssayUpsert {
	u.SetExcluded(essay.FieldUpdatedAt)
	return u
}

// SetContent sets the "content" field.
func (u *EssayUpsert) SetContent(v string) *EssayUpsert {
	u.Set(essay.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EssayUpsert) UpdateContent() *EssayUpsert {
	u.SetExcluded(essay.FieldContent)
	return u
}

// SetDate sets the "date" field.
func (u *EssayUpsert) SetDate(v time.Time) *EssayUpsert {
	u.Set(essay.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *EssayUpsert) UpdateDate() *EssayUpsert {
	u.SetExcluded(essay.FieldDate)
	return u
}

// SetImages sets the "images" field.
func (u *EssayUpsert) SetImages(v string) *EssayUpsert {
	u.Set(essay.FieldImages, v)
	return u
}

// UpdateImages sets the "images" field to the value that was provided on create.
func (u *EssayUpsert) UpdateImages() *EssayUpsert {
	u.SetExcluded(essay.FieldImages)
	return u
}

// ClearImages clears the value of the "images" field.
func (u *EssayUpsert) ClearImages() *EssayUpsert {
	u.SetNull(essay.FieldImages)
	return u
}

// SetLink sets the "link" field.
func (u *EssayUpsert) SetLink(v string) *EssayUpsert {
	u.Set(essay.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *EssayUpsert) UpdateLink() *EssayUpsert {
	u.SetExcluded(essay.FieldLink)
	return u
}

// ClearLink clears the value of the "link" field.
func (u *EssayUpsert) ClearLink() *EssayUpsert {
	u.SetNull(essay.FieldLink)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Essay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(essay.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EssayUpsertOne) UpdateNewValues() *EssayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(essay.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(essay.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Essay.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EssayUpsertOne) Ignore() *EssayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EssayUpsertOne) DoNothing() *EssayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EssayCreate.OnConflict
// documentation for more info.
func (u *EssayUpsertOne) Update(set func(*EssayUpsert)) *EssayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EssayUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EssayUpsertOne) SetDeletedAt(v time.Time) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateDeletedAt() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EssayUpsertOne) ClearDeletedAt() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EssayUpsertOne) SetUpdatedAt(v time.Time) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateUpdatedAt() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetContent sets the "content" field.
func (u *EssayUpsertOne) SetContent(v string) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateContent() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateContent()
	})
}

// SetDate sets the "date" field.
func (u *EssayUpsertOne) SetDate(v time.Time) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateDate() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateDate()
	})
}

// SetImages sets the "images" field.
func (u *EssayUpsertOne) SetImages(v string) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetImages(v)
	})
}

// UpdateImages sets the "images" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateImages() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateImages()
	})
}

// ClearImages clears the value of the "images" field.
func (u *EssayUpsertOne) ClearImages() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.ClearImages()
	})
}

// SetLink sets the "link" field.
func (u *EssayUpsertOne) SetLink(v string) *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *EssayUpsertOne) UpdateLink() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateLink()
	})
}

// ClearLink clears the value of the "link" field.
func (u *EssayUpsertOne) ClearLink() *EssayUpsertOne {
	return u.Update(func(s *EssayUpsert) {
		s.ClearLink()
	})
}

// Exec executes the query.
func (u *EssayUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EssayCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EssayUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EssayUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EssayUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EssayCreateBulk is the builder for creating many Essay entities in bulk.
type EssayCreateBulk struct {
	config
	err      error
	builders []*EssayCreate
	conflict []sql.ConflictOption
}

// Save creates the Essay entities in the database.
func (ecb *EssayCreateBulk) Save(ctx context.Context) ([]*Essay, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Essay, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EssayMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EssayCreateBulk) SaveX(ctx context.Context) []*Essay {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EssayCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EssayCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Essay.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EssayUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (ecb *EssayCreateBulk) OnConflict(opts ...sql.ConflictOption) *EssayUpsertBulk {
	ecb.conflict = opts
	return &EssayUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Essay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ecb *EssayCreateBulk) OnConflictColumns(columns ...string) *EssayUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &EssayUpsertBulk{
		create: ecb,
	}
}

// EssayUpsertBulk is the builder for "upsert"-ing
// a bulk of Essay nodes.
type EssayUpsertBulk struct {
	create *EssayCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Essay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(essay.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EssayUpsertBulk) UpdateNewValues() *EssayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(essay.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(essay.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Essay.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EssayUpsertBulk) Ignore() *EssayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EssayUpsertBulk) DoNothing() *EssayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EssayCreateBulk.OnConflict
// documentation for more info.
func (u *EssayUpsertBulk) Update(set func(*EssayUpsert)) *EssayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EssayUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EssayUpsertBulk) SetDeletedAt(v time.Time) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateDeletedAt() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EssayUpsertBulk) ClearDeletedAt() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EssayUpsertBulk) SetUpdatedAt(v time.Time) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateUpdatedAt() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetContent sets the "content" field.
func (u *EssayUpsertBulk) SetContent(v string) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateContent() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateContent()
	})
}

// SetDate sets the "date" field.
func (u *EssayUpsertBulk) SetDate(v time.Time) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateDate() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateDate()
	})
}

// SetImages sets the "images" field.
func (u *EssayUpsertBulk) SetImages(v string) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetImages(v)
	})
}

// UpdateImages sets the "images" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateImages() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateImages()
	})
}

// ClearImages clears the value of the "images" field.
func (u *EssayUpsertBulk) ClearImages() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.ClearImages()
	})
}

// SetLink sets the "link" field.
func (u *EssayUpsertBulk) SetLink(v string) *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *EssayUpsertBulk) UpdateLink() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.UpdateLink()
	})
}

// ClearLink clears the value of the "link" field.
func (u *EssayUpsertBulk) ClearLink() *EssayUpsertBulk {
	return u.Update(func(s *EssayUpsert) {
		s.ClearLink()
	})
}

// Exec executes the query.
func (u *EssayUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EssayCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EssayCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EssayUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
