// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/givemoney"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// GiveMoneyUpdate is the builder for updating GiveMoney entities.
type GiveMoneyUpdate struct {
	config
	hooks     []Hook
	mutation  *GiveMoneyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GiveMoneyUpdate builder.
func (gmu *GiveMoneyUpdate) Where(ps ...predicate.GiveMoney) *GiveMoneyUpdate {
	gmu.mutation.Where(ps...)
	return gmu
}

// SetDeletedAt sets the "deleted_at" field.
func (gmu *GiveMoneyUpdate) SetDeletedAt(t time.Time) *GiveMoneyUpdate {
	gmu.mutation.SetDeletedAt(t)
	return gmu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (gmu *GiveMoneyUpdate) SetNillableDeletedAt(t *time.Time) *GiveMoneyUpdate {
	if t != nil {
		gmu.SetDeletedAt(*t)
	}
	return gmu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (gmu *GiveMoneyUpdate) ClearDeletedAt() *GiveMoneyUpdate {
	gmu.mutation.ClearDeletedAt()
	return gmu
}

// SetUpdatedAt sets the "updated_at" field.
func (gmu *GiveMoneyUpdate) SetUpdatedAt(t time.Time) *GiveMoneyUpdate {
	gmu.mutation.SetUpdatedAt(t)
	return gmu
}

// SetNickname sets the "nickname" field.
func (gmu *GiveMoneyUpdate) SetNickname(s string) *GiveMoneyUpdate {
	gmu.mutation.SetNickname(s)
	return gmu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (gmu *GiveMoneyUpdate) SetNillableNickname(s *string) *GiveMoneyUpdate {
	if s != nil {
		gmu.SetNickname(*s)
	}
	return gmu
}

// SetFigure sets the "figure" field.
func (gmu *GiveMoneyUpdate) SetFigure(i int) *GiveMoneyUpdate {
	gmu.mutation.ResetFigure()
	gmu.mutation.SetFigure(i)
	return gmu
}

// SetNillableFigure sets the "figure" field if the given value is not nil.
func (gmu *GiveMoneyUpdate) SetNillableFigure(i *int) *GiveMoneyUpdate {
	if i != nil {
		gmu.SetFigure(*i)
	}
	return gmu
}

// AddFigure adds i to the "figure" field.
func (gmu *GiveMoneyUpdate) AddFigure(i int) *GiveMoneyUpdate {
	gmu.mutation.AddFigure(i)
	return gmu
}

// Mutation returns the GiveMoneyMutation object of the builder.
func (gmu *GiveMoneyUpdate) Mutation() *GiveMoneyMutation {
	return gmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gmu *GiveMoneyUpdate) Save(ctx context.Context) (int, error) {
	if err := gmu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, gmu.sqlSave, gmu.mutation, gmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gmu *GiveMoneyUpdate) SaveX(ctx context.Context) int {
	affected, err := gmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gmu *GiveMoneyUpdate) Exec(ctx context.Context) error {
	_, err := gmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmu *GiveMoneyUpdate) ExecX(ctx context.Context) {
	if err := gmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gmu *GiveMoneyUpdate) defaults() error {
	if _, ok := gmu.mutation.UpdatedAt(); !ok {
		if givemoney.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized givemoney.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := givemoney.UpdateDefaultUpdatedAt()
		gmu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (gmu *GiveMoneyUpdate) check() error {
	if v, ok := gmu.mutation.Nickname(); ok {
		if err := givemoney.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "GiveMoney.nickname": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (gmu *GiveMoneyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GiveMoneyUpdate {
	gmu.modifiers = append(gmu.modifiers, modifiers...)
	return gmu
}

func (gmu *GiveMoneyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := gmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(givemoney.Table, givemoney.Columns, sqlgraph.NewFieldSpec(givemoney.FieldID, field.TypeUint))
	if ps := gmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gmu.mutation.DeletedAt(); ok {
		_spec.SetField(givemoney.FieldDeletedAt, field.TypeTime, value)
	}
	if gmu.mutation.DeletedAtCleared() {
		_spec.ClearField(givemoney.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := gmu.mutation.UpdatedAt(); ok {
		_spec.SetField(givemoney.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := gmu.mutation.Nickname(); ok {
		_spec.SetField(givemoney.FieldNickname, field.TypeString, value)
	}
	if value, ok := gmu.mutation.Figure(); ok {
		_spec.SetField(givemoney.FieldFigure, field.TypeInt, value)
	}
	if value, ok := gmu.mutation.AddedFigure(); ok {
		_spec.AddField(givemoney.FieldFigure, field.TypeInt, value)
	}
	_spec.AddModifiers(gmu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, gmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{givemoney.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gmu.mutation.done = true
	return n, nil
}

// GiveMoneyUpdateOne is the builder for updating a single GiveMoney entity.
type GiveMoneyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GiveMoneyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (gmuo *GiveMoneyUpdateOne) SetDeletedAt(t time.Time) *GiveMoneyUpdateOne {
	gmuo.mutation.SetDeletedAt(t)
	return gmuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (gmuo *GiveMoneyUpdateOne) SetNillableDeletedAt(t *time.Time) *GiveMoneyUpdateOne {
	if t != nil {
		gmuo.SetDeletedAt(*t)
	}
	return gmuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (gmuo *GiveMoneyUpdateOne) ClearDeletedAt() *GiveMoneyUpdateOne {
	gmuo.mutation.ClearDeletedAt()
	return gmuo
}

// SetUpdatedAt sets the "updated_at" field.
func (gmuo *GiveMoneyUpdateOne) SetUpdatedAt(t time.Time) *GiveMoneyUpdateOne {
	gmuo.mutation.SetUpdatedAt(t)
	return gmuo
}

// SetNickname sets the "nickname" field.
func (gmuo *GiveMoneyUpdateOne) SetNickname(s string) *GiveMoneyUpdateOne {
	gmuo.mutation.SetNickname(s)
	return gmuo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (gmuo *GiveMoneyUpdateOne) SetNillableNickname(s *string) *GiveMoneyUpdateOne {
	if s != nil {
		gmuo.SetNickname(*s)
	}
	return gmuo
}

// SetFigure sets the "figure" field.
func (gmuo *GiveMoneyUpdateOne) SetFigure(i int) *GiveMoneyUpdateOne {
	gmuo.mutation.ResetFigure()
	gmuo.mutation.SetFigure(i)
	return gmuo
}

// SetNillableFigure sets the "figure" field if the given value is not nil.
func (gmuo *GiveMoneyUpdateOne) SetNillableFigure(i *int) *GiveMoneyUpdateOne {
	if i != nil {
		gmuo.SetFigure(*i)
	}
	return gmuo
}

// AddFigure adds i to the "figure" field.
func (gmuo *GiveMoneyUpdateOne) AddFigure(i int) *GiveMoneyUpdateOne {
	gmuo.mutation.AddFigure(i)
	return gmuo
}

// Mutation returns the GiveMoneyMutation object of the builder.
func (gmuo *GiveMoneyUpdateOne) Mutation() *GiveMoneyMutation {
	return gmuo.mutation
}

// Where appends a list predicates to the GiveMoneyUpdate builder.
func (gmuo *GiveMoneyUpdateOne) Where(ps ...predicate.GiveMoney) *GiveMoneyUpdateOne {
	gmuo.mutation.Where(ps...)
	return gmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (gmuo *GiveMoneyUpdateOne) Select(field string, fields ...string) *GiveMoneyUpdateOne {
	gmuo.fields = append([]string{field}, fields...)
	return gmuo
}

// Save executes the query and returns the updated GiveMoney entity.
func (gmuo *GiveMoneyUpdateOne) Save(ctx context.Context) (*GiveMoney, error) {
	if err := gmuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, gmuo.sqlSave, gmuo.mutation, gmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gmuo *GiveMoneyUpdateOne) SaveX(ctx context.Context) *GiveMoney {
	node, err := gmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (gmuo *GiveMoneyUpdateOne) Exec(ctx context.Context) error {
	_, err := gmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmuo *GiveMoneyUpdateOne) ExecX(ctx context.Context) {
	if err := gmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gmuo *GiveMoneyUpdateOne) defaults() error {
	if _, ok := gmuo.mutation.UpdatedAt(); !ok {
		if givemoney.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized givemoney.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := givemoney.UpdateDefaultUpdatedAt()
		gmuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (gmuo *GiveMoneyUpdateOne) check() error {
	if v, ok := gmuo.mutation.Nickname(); ok {
		if err := givemoney.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "GiveMoney.nickname": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (gmuo *GiveMoneyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GiveMoneyUpdateOne {
	gmuo.modifiers = append(gmuo.modifiers, modifiers...)
	return gmuo
}

func (gmuo *GiveMoneyUpdateOne) sqlSave(ctx context.Context) (_node *GiveMoney, err error) {
	if err := gmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(givemoney.Table, givemoney.Columns, sqlgraph.NewFieldSpec(givemoney.FieldID, field.TypeUint))
	id, ok := gmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GiveMoney.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := gmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, givemoney.FieldID)
		for _, f := range fields {
			if !givemoney.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != givemoney.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := gmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gmuo.mutation.DeletedAt(); ok {
		_spec.SetField(givemoney.FieldDeletedAt, field.TypeTime, value)
	}
	if gmuo.mutation.DeletedAtCleared() {
		_spec.ClearField(givemoney.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := gmuo.mutation.UpdatedAt(); ok {
		_spec.SetField(givemoney.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := gmuo.mutation.Nickname(); ok {
		_spec.SetField(givemoney.FieldNickname, field.TypeString, value)
	}
	if value, ok := gmuo.mutation.Figure(); ok {
		_spec.SetField(givemoney.FieldFigure, field.TypeInt, value)
	}
	if value, ok := gmuo.mutation.AddedFigure(); ok {
		_spec.AddField(givemoney.FieldFigure, field.TypeInt, value)
	}
	_spec.AddModifiers(gmuo.modifiers...)
	_node = &GiveMoney{config: gmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, gmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{givemoney.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	gmuo.mutation.done = true
	return _node, nil
}
