// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/link"
	"github.com/anzhiyu-c/anheyu-app/ent/linkcategory"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
)

// LinkCategoryQuery is the builder for querying LinkCategory entities.
type LinkCategoryQuery struct {
	config
	ctx        *QueryContext
	order      []linkcategory.OrderOption
	inters     []Interceptor
	predicates []predicate.LinkCategory
	withLinks  *LinkQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LinkCategoryQuery builder.
func (lcq *LinkCategoryQuery) Where(ps ...predicate.LinkCategory) *LinkCategoryQuery {
	lcq.predicates = append(lcq.predicates, ps...)
	return lcq
}

// Limit the number of records to be returned by this query.
func (lcq *LinkCategoryQuery) Limit(limit int) *LinkCategoryQuery {
	lcq.ctx.Limit = &limit
	return lcq
}

// Offset to start from.
func (lcq *LinkCategoryQuery) Offset(offset int) *LinkCategoryQuery {
	lcq.ctx.Offset = &offset
	return lcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lcq *LinkCategoryQuery) Unique(unique bool) *LinkCategoryQuery {
	lcq.ctx.Unique = &unique
	return lcq
}

// Order specifies how the records should be ordered.
func (lcq *LinkCategoryQuery) Order(o ...linkcategory.OrderOption) *LinkCategoryQuery {
	lcq.order = append(lcq.order, o...)
	return lcq
}

// QueryLinks chains the current query on the "links" edge.
func (lcq *LinkCategoryQuery) QueryLinks() *LinkQuery {
	query := (&LinkClient{config: lcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(linkcategory.Table, linkcategory.FieldID, selector),
			sqlgraph.To(link.Table, link.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, linkcategory.LinksTable, linkcategory.LinksColumn),
		)
		fromU = sqlgraph.SetNeighbors(lcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LinkCategory entity from the query.
// Returns a *NotFoundError when no LinkCategory was found.
func (lcq *LinkCategoryQuery) First(ctx context.Context) (*LinkCategory, error) {
	nodes, err := lcq.Limit(1).All(setContextOp(ctx, lcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linkcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lcq *LinkCategoryQuery) FirstX(ctx context.Context) *LinkCategory {
	node, err := lcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LinkCategory ID from the query.
// Returns a *NotFoundError when no LinkCategory ID was found.
func (lcq *LinkCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lcq.Limit(1).IDs(setContextOp(ctx, lcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linkcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lcq *LinkCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := lcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LinkCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LinkCategory entity is found.
// Returns a *NotFoundError when no LinkCategory entities are found.
func (lcq *LinkCategoryQuery) Only(ctx context.Context) (*LinkCategory, error) {
	nodes, err := lcq.Limit(2).All(setContextOp(ctx, lcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linkcategory.Label}
	default:
		return nil, &NotSingularError{linkcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lcq *LinkCategoryQuery) OnlyX(ctx context.Context) *LinkCategory {
	node, err := lcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LinkCategory ID in the query.
// Returns a *NotSingularError when more than one LinkCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (lcq *LinkCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lcq.Limit(2).IDs(setContextOp(ctx, lcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linkcategory.Label}
	default:
		err = &NotSingularError{linkcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lcq *LinkCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := lcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LinkCategories.
func (lcq *LinkCategoryQuery) All(ctx context.Context) ([]*LinkCategory, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryAll)
	if err := lcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LinkCategory, *LinkCategoryQuery]()
	return withInterceptors[[]*LinkCategory](ctx, lcq, qr, lcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lcq *LinkCategoryQuery) AllX(ctx context.Context) []*LinkCategory {
	nodes, err := lcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LinkCategory IDs.
func (lcq *LinkCategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lcq.ctx.Unique == nil && lcq.path != nil {
		lcq.Unique(true)
	}
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryIDs)
	if err = lcq.Select(linkcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lcq *LinkCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := lcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lcq *LinkCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryCount)
	if err := lcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lcq, querierCount[*LinkCategoryQuery](), lcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lcq *LinkCategoryQuery) CountX(ctx context.Context) int {
	count, err := lcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lcq *LinkCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lcq.ctx, ent.OpQueryExist)
	switch _, err := lcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lcq *LinkCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := lcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LinkCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lcq *LinkCategoryQuery) Clone() *LinkCategoryQuery {
	if lcq == nil {
		return nil
	}
	return &LinkCategoryQuery{
		config:     lcq.config,
		ctx:        lcq.ctx.Clone(),
		order:      append([]linkcategory.OrderOption{}, lcq.order...),
		inters:     append([]Interceptor{}, lcq.inters...),
		predicates: append([]predicate.LinkCategory{}, lcq.predicates...),
		withLinks:  lcq.withLinks.Clone(),
		// clone intermediate query.
		sql:       lcq.sql.Clone(),
		path:      lcq.path,
		modifiers: append([]func(*sql.Selector){}, lcq.modifiers...),
	}
}

// WithLinks tells the query-builder to eager-load the nodes that are connected to
// the "links" edge. The optional arguments are used to configure the query builder of the edge.
func (lcq *LinkCategoryQuery) WithLinks(opts ...func(*LinkQuery)) *LinkCategoryQuery {
	query := (&LinkClient{config: lcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lcq.withLinks = query
	return lcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LinkCategory.Query().
//		GroupBy(linkcategory.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lcq *LinkCategoryQuery) GroupBy(field string, fields ...string) *LinkCategoryGroupBy {
	lcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LinkCategoryGroupBy{build: lcq}
	grbuild.flds = &lcq.ctx.Fields
	grbuild.label = linkcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LinkCategory.Query().
//		Select(linkcategory.FieldName).
//		Scan(ctx, &v)
func (lcq *LinkCategoryQuery) Select(fields ...string) *LinkCategorySelect {
	lcq.ctx.Fields = append(lcq.ctx.Fields, fields...)
	sbuild := &LinkCategorySelect{LinkCategoryQuery: lcq}
	sbuild.label = linkcategory.Label
	sbuild.flds, sbuild.scan = &lcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LinkCategorySelect configured with the given aggregations.
func (lcq *LinkCategoryQuery) Aggregate(fns ...AggregateFunc) *LinkCategorySelect {
	return lcq.Select().Aggregate(fns...)
}

func (lcq *LinkCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lcq); err != nil {
				return err
			}
		}
	}
	for _, f := range lcq.ctx.Fields {
		if !linkcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lcq.path != nil {
		prev, err := lcq.path(ctx)
		if err != nil {
			return err
		}
		lcq.sql = prev
	}
	return nil
}

func (lcq *LinkCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LinkCategory, error) {
	var (
		nodes       = []*LinkCategory{}
		_spec       = lcq.querySpec()
		loadedTypes = [1]bool{
			lcq.withLinks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LinkCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LinkCategory{config: lcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(lcq.modifiers) > 0 {
		_spec.Modifiers = lcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lcq.withLinks; query != nil {
		if err := lcq.loadLinks(ctx, query, nodes,
			func(n *LinkCategory) { n.Edges.Links = []*Link{} },
			func(n *LinkCategory, e *Link) { n.Edges.Links = append(n.Edges.Links, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lcq *LinkCategoryQuery) loadLinks(ctx context.Context, query *LinkQuery, nodes []*LinkCategory, init func(*LinkCategory), assign func(*LinkCategory, *Link)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LinkCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Link(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(linkcategory.LinksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.link_category_links
		if fk == nil {
			return fmt.Errorf(`foreign-key "link_category_links" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "link_category_links" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lcq *LinkCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lcq.querySpec()
	if len(lcq.modifiers) > 0 {
		_spec.Modifiers = lcq.modifiers
	}
	_spec.Node.Columns = lcq.ctx.Fields
	if len(lcq.ctx.Fields) > 0 {
		_spec.Unique = lcq.ctx.Unique != nil && *lcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lcq.driver, _spec)
}

func (lcq *LinkCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(linkcategory.Table, linkcategory.Columns, sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeInt))
	_spec.From = lcq.sql
	if unique := lcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lcq.path != nil {
		_spec.Unique = true
	}
	if fields := lcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkcategory.FieldID)
		for i := range fields {
			if fields[i] != linkcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lcq *LinkCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lcq.driver.Dialect())
	t1 := builder.Table(linkcategory.Table)
	columns := lcq.ctx.Fields
	if len(columns) == 0 {
		columns = linkcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lcq.sql != nil {
		selector = lcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lcq.ctx.Unique != nil && *lcq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range lcq.modifiers {
		m(selector)
	}
	for _, p := range lcq.predicates {
		p(selector)
	}
	for _, p := range lcq.order {
		p(selector)
	}
	if offset := lcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lcq *LinkCategoryQuery) Modify(modifiers ...func(s *sql.Selector)) *LinkCategorySelect {
	lcq.modifiers = append(lcq.modifiers, modifiers...)
	return lcq.Select()
}

// LinkCategoryGroupBy is the group-by builder for LinkCategory entities.
type LinkCategoryGroupBy struct {
	selector
	build *LinkCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lcgb *LinkCategoryGroupBy) Aggregate(fns ...AggregateFunc) *LinkCategoryGroupBy {
	lcgb.fns = append(lcgb.fns, fns...)
	return lcgb
}

// Scan applies the selector query and scans the result into the given value.
func (lcgb *LinkCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lcgb.build.ctx, ent.OpQueryGroupBy)
	if err := lcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LinkCategoryQuery, *LinkCategoryGroupBy](ctx, lcgb.build, lcgb, lcgb.build.inters, v)
}

func (lcgb *LinkCategoryGroupBy) sqlScan(ctx context.Context, root *LinkCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lcgb.fns))
	for _, fn := range lcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lcgb.flds)+len(lcgb.fns))
		for _, f := range *lcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LinkCategorySelect is the builder for selecting fields of LinkCategory entities.
type LinkCategorySelect struct {
	*LinkCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lcs *LinkCategorySelect) Aggregate(fns ...AggregateFunc) *LinkCategorySelect {
	lcs.fns = append(lcs.fns, fns...)
	return lcs
}

// Scan applies the selector query and scans the result into the given value.
func (lcs *LinkCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lcs.ctx, ent.OpQuerySelect)
	if err := lcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LinkCategoryQuery, *LinkCategorySelect](ctx, lcs.LinkCategoryQuery, lcs, lcs.inters, v)
}

func (lcs *LinkCategorySelect) sqlScan(ctx context.Context, root *LinkCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lcs.fns))
	for _, fn := range lcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lcs *LinkCategorySelect) Modify(modifiers ...func(s *sql.Selector)) *LinkCategorySelect {
	lcs.modifiers = append(lcs.modifiers, modifiers...)
	return lcs
}
