// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/link"
	"github.com/anzhiyu-c/anheyu-app/ent/linktag"
)

// LinkTagCreate is the builder for creating a LinkTag entity.
type LinkTagCreate struct {
	config
	mutation *LinkTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (ltc *LinkTagCreate) SetName(s string) *LinkTagCreate {
	ltc.mutation.SetName(s)
	return ltc
}

// SetColor sets the "color" field.
func (ltc *LinkTagCreate) SetColor(s string) *LinkTagCreate {
	ltc.mutation.SetColor(s)
	return ltc
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (ltc *LinkTagCreate) SetNillableColor(s *string) *LinkTagCreate {
	if s != nil {
		ltc.SetColor(*s)
	}
	return ltc
}

// AddLinkIDs adds the "links" edge to the Link entity by IDs.
func (ltc *LinkTagCreate) AddLinkIDs(ids ...int) *LinkTagCreate {
	ltc.mutation.AddLinkIDs(ids...)
	return ltc
}

// AddLinks adds the "links" edges to the Link entity.
func (ltc *LinkTagCreate) AddLinks(l ...*Link) *LinkTagCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return ltc.AddLinkIDs(ids...)
}

// Mutation returns the LinkTagMutation object of the builder.
func (ltc *LinkTagCreate) Mutation() *LinkTagMutation {
	return ltc.mutation
}

// Save creates the LinkTag in the database.
func (ltc *LinkTagCreate) Save(ctx context.Context) (*LinkTag, error) {
	ltc.defaults()
	return withHooks(ctx, ltc.sqlSave, ltc.mutation, ltc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ltc *LinkTagCreate) SaveX(ctx context.Context) *LinkTag {
	v, err := ltc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltc *LinkTagCreate) Exec(ctx context.Context) error {
	_, err := ltc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltc *LinkTagCreate) ExecX(ctx context.Context) {
	if err := ltc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ltc *LinkTagCreate) defaults() {
	if _, ok := ltc.mutation.Color(); !ok {
		v := linktag.DefaultColor
		ltc.mutation.SetColor(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ltc *LinkTagCreate) check() error {
	if _, ok := ltc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LinkTag.name"`)}
	}
	if v, ok := ltc.mutation.Name(); ok {
		if err := linktag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LinkTag.name": %w`, err)}
		}
	}
	if _, ok := ltc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "LinkTag.color"`)}
	}
	return nil
}

func (ltc *LinkTagCreate) sqlSave(ctx context.Context) (*LinkTag, error) {
	if err := ltc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ltc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ltc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ltc.mutation.id = &_node.ID
	ltc.mutation.done = true
	return _node, nil
}

func (ltc *LinkTagCreate) createSpec() (*LinkTag, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkTag{config: ltc.config}
		_spec = sqlgraph.NewCreateSpec(linktag.Table, sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ltc.conflict
	if value, ok := ltc.mutation.Name(); ok {
		_spec.SetField(linktag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ltc.mutation.Color(); ok {
		_spec.SetField(linktag.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if nodes := ltc.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   linktag.LinksTable,
			Columns: linktag.LinksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkTag.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkTagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ltc *LinkTagCreate) OnConflict(opts ...sql.ConflictOption) *LinkTagUpsertOne {
	ltc.conflict = opts
	return &LinkTagUpsertOne{
		create: ltc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ltc *LinkTagCreate) OnConflictColumns(columns ...string) *LinkTagUpsertOne {
	ltc.conflict = append(ltc.conflict, sql.ConflictColumns(columns...))
	return &LinkTagUpsertOne{
		create: ltc,
	}
}

type (
	// LinkTagUpsertOne is the builder for "upsert"-ing
	//  one LinkTag node.
	LinkTagUpsertOne struct {
		create *LinkTagCreate
	}

	// LinkTagUpsert is the "OnConflict" setter.
	LinkTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *LinkTagUpsert) SetName(v string) *LinkTagUpsert {
	u.Set(linktag.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkTagUpsert) UpdateName() *LinkTagUpsert {
	u.SetExcluded(linktag.FieldName)
	return u
}

// SetColor sets the "color" field.
func (u *LinkTagUpsert) SetColor(v string) *LinkTagUpsert {
	u.Set(linktag.FieldColor, v)
	return u
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *LinkTagUpsert) UpdateColor() *LinkTagUpsert {
	u.SetExcluded(linktag.FieldColor)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkTagUpsertOne) UpdateNewValues() *LinkTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkTagUpsertOne) Ignore() *LinkTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkTagUpsertOne) DoNothing() *LinkTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkTagCreate.OnConflict
// documentation for more info.
func (u *LinkTagUpsertOne) Update(set func(*LinkTagUpsert)) *LinkTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LinkTagUpsertOne) SetName(v string) *LinkTagUpsertOne {
	return u.Update(func(s *LinkTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkTagUpsertOne) UpdateName() *LinkTagUpsertOne {
	return u.Update(func(s *LinkTagUpsert) {
		s.UpdateName()
	})
}

// SetColor sets the "color" field.
func (u *LinkTagUpsertOne) SetColor(v string) *LinkTagUpsertOne {
	return u.Update(func(s *LinkTagUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *LinkTagUpsertOne) UpdateColor() *LinkTagUpsertOne {
	return u.Update(func(s *LinkTagUpsert) {
		s.UpdateColor()
	})
}

// Exec executes the query.
func (u *LinkTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkTagUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkTagUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkTagCreateBulk is the builder for creating many LinkTag entities in bulk.
type LinkTagCreateBulk struct {
	config
	err      error
	builders []*LinkTagCreate
	conflict []sql.ConflictOption
}

// Save creates the LinkTag entities in the database.
func (ltcb *LinkTagCreateBulk) Save(ctx context.Context) ([]*LinkTag, error) {
	if ltcb.err != nil {
		return nil, ltcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ltcb.builders))
	nodes := make([]*LinkTag, len(ltcb.builders))
	mutators := make([]Mutator, len(ltcb.builders))
	for i := range ltcb.builders {
		func(i int, root context.Context) {
			builder := ltcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ltcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ltcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ltcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ltcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ltcb *LinkTagCreateBulk) SaveX(ctx context.Context) []*LinkTag {
	v, err := ltcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltcb *LinkTagCreateBulk) Exec(ctx context.Context) error {
	_, err := ltcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltcb *LinkTagCreateBulk) ExecX(ctx context.Context) {
	if err := ltcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkTagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ltcb *LinkTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkTagUpsertBulk {
	ltcb.conflict = opts
	return &LinkTagUpsertBulk{
		create: ltcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ltcb *LinkTagCreateBulk) OnConflictColumns(columns ...string) *LinkTagUpsertBulk {
	ltcb.conflict = append(ltcb.conflict, sql.ConflictColumns(columns...))
	return &LinkTagUpsertBulk{
		create: ltcb,
	}
}

// LinkTagUpsertBulk is the builder for "upsert"-ing
// a bulk of LinkTag nodes.
type LinkTagUpsertBulk struct {
	create *LinkTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkTagUpsertBulk) UpdateNewValues() *LinkTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkTagUpsertBulk) Ignore() *LinkTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkTagUpsertBulk) DoNothing() *LinkTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkTagCreateBulk.OnConflict
// documentation for more info.
func (u *LinkTagUpsertBulk) Update(set func(*LinkTagUpsert)) *LinkTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LinkTagUpsertBulk) SetName(v string) *LinkTagUpsertBulk {
	return u.Update(func(s *LinkTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkTagUpsertBulk) UpdateName() *LinkTagUpsertBulk {
	return u.Update(func(s *LinkTagUpsert) {
		s.UpdateName()
	})
}

// SetColor sets the "color" field.
func (u *LinkTagUpsertBulk) SetColor(v string) *LinkTagUpsertBulk {
	return u.Update(func(s *LinkTagUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *LinkTagUpsertBulk) UpdateColor() *LinkTagUpsertBulk {
	return u.Update(func(s *LinkTagUpsert) {
		s.UpdateColor()
	})
}

// Exec executes the query.
func (u *LinkTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
