// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/notificationtype"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/usernotificationconfig"
)

// NotificationTypeUpdate is the builder for updating NotificationType entities.
type NotificationTypeUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationTypeUpdate builder.
func (ntu *NotificationTypeUpdate) Where(ps ...predicate.NotificationType) *NotificationTypeUpdate {
	ntu.mutation.Where(ps...)
	return ntu
}

// SetUpdatedAt sets the "updated_at" field.
func (ntu *NotificationTypeUpdate) SetUpdatedAt(t time.Time) *NotificationTypeUpdate {
	ntu.mutation.SetUpdatedAt(t)
	return ntu
}

// SetCode sets the "code" field.
func (ntu *NotificationTypeUpdate) SetCode(s string) *NotificationTypeUpdate {
	ntu.mutation.SetCode(s)
	return ntu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableCode(s *string) *NotificationTypeUpdate {
	if s != nil {
		ntu.SetCode(*s)
	}
	return ntu
}

// SetName sets the "name" field.
func (ntu *NotificationTypeUpdate) SetName(s string) *NotificationTypeUpdate {
	ntu.mutation.SetName(s)
	return ntu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableName(s *string) *NotificationTypeUpdate {
	if s != nil {
		ntu.SetName(*s)
	}
	return ntu
}

// SetDescription sets the "description" field.
func (ntu *NotificationTypeUpdate) SetDescription(s string) *NotificationTypeUpdate {
	ntu.mutation.SetDescription(s)
	return ntu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableDescription(s *string) *NotificationTypeUpdate {
	if s != nil {
		ntu.SetDescription(*s)
	}
	return ntu
}

// ClearDescription clears the value of the "description" field.
func (ntu *NotificationTypeUpdate) ClearDescription() *NotificationTypeUpdate {
	ntu.mutation.ClearDescription()
	return ntu
}

// SetCategory sets the "category" field.
func (ntu *NotificationTypeUpdate) SetCategory(s string) *NotificationTypeUpdate {
	ntu.mutation.SetCategory(s)
	return ntu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableCategory(s *string) *NotificationTypeUpdate {
	if s != nil {
		ntu.SetCategory(*s)
	}
	return ntu
}

// SetIsActive sets the "is_active" field.
func (ntu *NotificationTypeUpdate) SetIsActive(b bool) *NotificationTypeUpdate {
	ntu.mutation.SetIsActive(b)
	return ntu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableIsActive(b *bool) *NotificationTypeUpdate {
	if b != nil {
		ntu.SetIsActive(*b)
	}
	return ntu
}

// SetDefaultEnabled sets the "default_enabled" field.
func (ntu *NotificationTypeUpdate) SetDefaultEnabled(b bool) *NotificationTypeUpdate {
	ntu.mutation.SetDefaultEnabled(b)
	return ntu
}

// SetNillableDefaultEnabled sets the "default_enabled" field if the given value is not nil.
func (ntu *NotificationTypeUpdate) SetNillableDefaultEnabled(b *bool) *NotificationTypeUpdate {
	if b != nil {
		ntu.SetDefaultEnabled(*b)
	}
	return ntu
}

// SetSupportedChannels sets the "supported_channels" field.
func (ntu *NotificationTypeUpdate) SetSupportedChannels(s []string) *NotificationTypeUpdate {
	ntu.mutation.SetSupportedChannels(s)
	return ntu
}

// AppendSupportedChannels appends s to the "supported_channels" field.
func (ntu *NotificationTypeUpdate) AppendSupportedChannels(s []string) *NotificationTypeUpdate {
	ntu.mutation.AppendSupportedChannels(s)
	return ntu
}

// ClearSupportedChannels clears the value of the "supported_channels" field.
func (ntu *NotificationTypeUpdate) ClearSupportedChannels() *NotificationTypeUpdate {
	ntu.mutation.ClearSupportedChannels()
	return ntu
}

// AddUserConfigIDs adds the "user_configs" edge to the UserNotificationConfig entity by IDs.
func (ntu *NotificationTypeUpdate) AddUserConfigIDs(ids ...uint) *NotificationTypeUpdate {
	ntu.mutation.AddUserConfigIDs(ids...)
	return ntu
}

// AddUserConfigs adds the "user_configs" edges to the UserNotificationConfig entity.
func (ntu *NotificationTypeUpdate) AddUserConfigs(u ...*UserNotificationConfig) *NotificationTypeUpdate {
	ids := make([]uint, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ntu.AddUserConfigIDs(ids...)
}

// Mutation returns the NotificationTypeMutation object of the builder.
func (ntu *NotificationTypeUpdate) Mutation() *NotificationTypeMutation {
	return ntu.mutation
}

// ClearUserConfigs clears all "user_configs" edges to the UserNotificationConfig entity.
func (ntu *NotificationTypeUpdate) ClearUserConfigs() *NotificationTypeUpdate {
	ntu.mutation.ClearUserConfigs()
	return ntu
}

// RemoveUserConfigIDs removes the "user_configs" edge to UserNotificationConfig entities by IDs.
func (ntu *NotificationTypeUpdate) RemoveUserConfigIDs(ids ...uint) *NotificationTypeUpdate {
	ntu.mutation.RemoveUserConfigIDs(ids...)
	return ntu
}

// RemoveUserConfigs removes "user_configs" edges to UserNotificationConfig entities.
func (ntu *NotificationTypeUpdate) RemoveUserConfigs(u ...*UserNotificationConfig) *NotificationTypeUpdate {
	ids := make([]uint, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ntu.RemoveUserConfigIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ntu *NotificationTypeUpdate) Save(ctx context.Context) (int, error) {
	ntu.defaults()
	return withHooks(ctx, ntu.sqlSave, ntu.mutation, ntu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntu *NotificationTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := ntu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ntu *NotificationTypeUpdate) Exec(ctx context.Context) error {
	_, err := ntu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntu *NotificationTypeUpdate) ExecX(ctx context.Context) {
	if err := ntu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ntu *NotificationTypeUpdate) defaults() {
	if _, ok := ntu.mutation.UpdatedAt(); !ok {
		v := notificationtype.UpdateDefaultUpdatedAt()
		ntu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ntu *NotificationTypeUpdate) check() error {
	if v, ok := ntu.mutation.Code(); ok {
		if err := notificationtype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "NotificationType.code": %w`, err)}
		}
	}
	if v, ok := ntu.mutation.Name(); ok {
		if err := notificationtype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationType.name": %w`, err)}
		}
	}
	if v, ok := ntu.mutation.Description(); ok {
		if err := notificationtype.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "NotificationType.description": %w`, err)}
		}
	}
	if v, ok := ntu.mutation.Category(); ok {
		if err := notificationtype.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "NotificationType.category": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ntu *NotificationTypeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationTypeUpdate {
	ntu.modifiers = append(ntu.modifiers, modifiers...)
	return ntu
}

func (ntu *NotificationTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ntu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtype.Table, notificationtype.Columns, sqlgraph.NewFieldSpec(notificationtype.FieldID, field.TypeUint))
	if ps := ntu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntu.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ntu.mutation.Code(); ok {
		_spec.SetField(notificationtype.FieldCode, field.TypeString, value)
	}
	if value, ok := ntu.mutation.Name(); ok {
		_spec.SetField(notificationtype.FieldName, field.TypeString, value)
	}
	if value, ok := ntu.mutation.Description(); ok {
		_spec.SetField(notificationtype.FieldDescription, field.TypeString, value)
	}
	if ntu.mutation.DescriptionCleared() {
		_spec.ClearField(notificationtype.FieldDescription, field.TypeString)
	}
	if value, ok := ntu.mutation.Category(); ok {
		_spec.SetField(notificationtype.FieldCategory, field.TypeString, value)
	}
	if value, ok := ntu.mutation.IsActive(); ok {
		_spec.SetField(notificationtype.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ntu.mutation.DefaultEnabled(); ok {
		_spec.SetField(notificationtype.FieldDefaultEnabled, field.TypeBool, value)
	}
	if value, ok := ntu.mutation.SupportedChannels(); ok {
		_spec.SetField(notificationtype.FieldSupportedChannels, field.TypeJSON, value)
	}
	if value, ok := ntu.mutation.AppendedSupportedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationtype.FieldSupportedChannels, value)
		})
	}
	if ntu.mutation.SupportedChannelsCleared() {
		_spec.ClearField(notificationtype.FieldSupportedChannels, field.TypeJSON)
	}
	if ntu.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ntu.mutation.RemovedUserConfigsIDs(); len(nodes) > 0 && !ntu.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ntu.mutation.UserConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ntu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ntu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ntu.mutation.done = true
	return n, nil
}

// NotificationTypeUpdateOne is the builder for updating a single NotificationType entity.
type NotificationTypeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (ntuo *NotificationTypeUpdateOne) SetUpdatedAt(t time.Time) *NotificationTypeUpdateOne {
	ntuo.mutation.SetUpdatedAt(t)
	return ntuo
}

// SetCode sets the "code" field.
func (ntuo *NotificationTypeUpdateOne) SetCode(s string) *NotificationTypeUpdateOne {
	ntuo.mutation.SetCode(s)
	return ntuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableCode(s *string) *NotificationTypeUpdateOne {
	if s != nil {
		ntuo.SetCode(*s)
	}
	return ntuo
}

// SetName sets the "name" field.
func (ntuo *NotificationTypeUpdateOne) SetName(s string) *NotificationTypeUpdateOne {
	ntuo.mutation.SetName(s)
	return ntuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableName(s *string) *NotificationTypeUpdateOne {
	if s != nil {
		ntuo.SetName(*s)
	}
	return ntuo
}

// SetDescription sets the "description" field.
func (ntuo *NotificationTypeUpdateOne) SetDescription(s string) *NotificationTypeUpdateOne {
	ntuo.mutation.SetDescription(s)
	return ntuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableDescription(s *string) *NotificationTypeUpdateOne {
	if s != nil {
		ntuo.SetDescription(*s)
	}
	return ntuo
}

// ClearDescription clears the value of the "description" field.
func (ntuo *NotificationTypeUpdateOne) ClearDescription() *NotificationTypeUpdateOne {
	ntuo.mutation.ClearDescription()
	return ntuo
}

// SetCategory sets the "category" field.
func (ntuo *NotificationTypeUpdateOne) SetCategory(s string) *NotificationTypeUpdateOne {
	ntuo.mutation.SetCategory(s)
	return ntuo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableCategory(s *string) *NotificationTypeUpdateOne {
	if s != nil {
		ntuo.SetCategory(*s)
	}
	return ntuo
}

// SetIsActive sets the "is_active" field.
func (ntuo *NotificationTypeUpdateOne) SetIsActive(b bool) *NotificationTypeUpdateOne {
	ntuo.mutation.SetIsActive(b)
	return ntuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableIsActive(b *bool) *NotificationTypeUpdateOne {
	if b != nil {
		ntuo.SetIsActive(*b)
	}
	return ntuo
}

// SetDefaultEnabled sets the "default_enabled" field.
func (ntuo *NotificationTypeUpdateOne) SetDefaultEnabled(b bool) *NotificationTypeUpdateOne {
	ntuo.mutation.SetDefaultEnabled(b)
	return ntuo
}

// SetNillableDefaultEnabled sets the "default_enabled" field if the given value is not nil.
func (ntuo *NotificationTypeUpdateOne) SetNillableDefaultEnabled(b *bool) *NotificationTypeUpdateOne {
	if b != nil {
		ntuo.SetDefaultEnabled(*b)
	}
	return ntuo
}

// SetSupportedChannels sets the "supported_channels" field.
func (ntuo *NotificationTypeUpdateOne) SetSupportedChannels(s []string) *NotificationTypeUpdateOne {
	ntuo.mutation.SetSupportedChannels(s)
	return ntuo
}

// AppendSupportedChannels appends s to the "supported_channels" field.
func (ntuo *NotificationTypeUpdateOne) AppendSupportedChannels(s []string) *NotificationTypeUpdateOne {
	ntuo.mutation.AppendSupportedChannels(s)
	return ntuo
}

// ClearSupportedChannels clears the value of the "supported_channels" field.
func (ntuo *NotificationTypeUpdateOne) ClearSupportedChannels() *NotificationTypeUpdateOne {
	ntuo.mutation.ClearSupportedChannels()
	return ntuo
}

// AddUserConfigIDs adds the "user_configs" edge to the UserNotificationConfig entity by IDs.
func (ntuo *NotificationTypeUpdateOne) AddUserConfigIDs(ids ...uint) *NotificationTypeUpdateOne {
	ntuo.mutation.AddUserConfigIDs(ids...)
	return ntuo
}

// AddUserConfigs adds the "user_configs" edges to the UserNotificationConfig entity.
func (ntuo *NotificationTypeUpdateOne) AddUserConfigs(u ...*UserNotificationConfig) *NotificationTypeUpdateOne {
	ids := make([]uint, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ntuo.AddUserConfigIDs(ids...)
}

// Mutation returns the NotificationTypeMutation object of the builder.
func (ntuo *NotificationTypeUpdateOne) Mutation() *NotificationTypeMutation {
	return ntuo.mutation
}

// ClearUserConfigs clears all "user_configs" edges to the UserNotificationConfig entity.
func (ntuo *NotificationTypeUpdateOne) ClearUserConfigs() *NotificationTypeUpdateOne {
	ntuo.mutation.ClearUserConfigs()
	return ntuo
}

// RemoveUserConfigIDs removes the "user_configs" edge to UserNotificationConfig entities by IDs.
func (ntuo *NotificationTypeUpdateOne) RemoveUserConfigIDs(ids ...uint) *NotificationTypeUpdateOne {
	ntuo.mutation.RemoveUserConfigIDs(ids...)
	return ntuo
}

// RemoveUserConfigs removes "user_configs" edges to UserNotificationConfig entities.
func (ntuo *NotificationTypeUpdateOne) RemoveUserConfigs(u ...*UserNotificationConfig) *NotificationTypeUpdateOne {
	ids := make([]uint, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ntuo.RemoveUserConfigIDs(ids...)
}

// Where appends a list predicates to the NotificationTypeUpdate builder.
func (ntuo *NotificationTypeUpdateOne) Where(ps ...predicate.NotificationType) *NotificationTypeUpdateOne {
	ntuo.mutation.Where(ps...)
	return ntuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ntuo *NotificationTypeUpdateOne) Select(field string, fields ...string) *NotificationTypeUpdateOne {
	ntuo.fields = append([]string{field}, fields...)
	return ntuo
}

// Save executes the query and returns the updated NotificationType entity.
func (ntuo *NotificationTypeUpdateOne) Save(ctx context.Context) (*NotificationType, error) {
	ntuo.defaults()
	return withHooks(ctx, ntuo.sqlSave, ntuo.mutation, ntuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ntuo *NotificationTypeUpdateOne) SaveX(ctx context.Context) *NotificationType {
	node, err := ntuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ntuo *NotificationTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := ntuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntuo *NotificationTypeUpdateOne) ExecX(ctx context.Context) {
	if err := ntuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ntuo *NotificationTypeUpdateOne) defaults() {
	if _, ok := ntuo.mutation.UpdatedAt(); !ok {
		v := notificationtype.UpdateDefaultUpdatedAt()
		ntuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ntuo *NotificationTypeUpdateOne) check() error {
	if v, ok := ntuo.mutation.Code(); ok {
		if err := notificationtype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "NotificationType.code": %w`, err)}
		}
	}
	if v, ok := ntuo.mutation.Name(); ok {
		if err := notificationtype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationType.name": %w`, err)}
		}
	}
	if v, ok := ntuo.mutation.Description(); ok {
		if err := notificationtype.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "NotificationType.description": %w`, err)}
		}
	}
	if v, ok := ntuo.mutation.Category(); ok {
		if err := notificationtype.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "NotificationType.category": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ntuo *NotificationTypeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationTypeUpdateOne {
	ntuo.modifiers = append(ntuo.modifiers, modifiers...)
	return ntuo
}

func (ntuo *NotificationTypeUpdateOne) sqlSave(ctx context.Context) (_node *NotificationType, err error) {
	if err := ntuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtype.Table, notificationtype.Columns, sqlgraph.NewFieldSpec(notificationtype.FieldID, field.TypeUint))
	id, ok := ntuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ntuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationtype.FieldID)
		for _, f := range fields {
			if !notificationtype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationtype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ntuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ntuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ntuo.mutation.Code(); ok {
		_spec.SetField(notificationtype.FieldCode, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.Name(); ok {
		_spec.SetField(notificationtype.FieldName, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.Description(); ok {
		_spec.SetField(notificationtype.FieldDescription, field.TypeString, value)
	}
	if ntuo.mutation.DescriptionCleared() {
		_spec.ClearField(notificationtype.FieldDescription, field.TypeString)
	}
	if value, ok := ntuo.mutation.Category(); ok {
		_spec.SetField(notificationtype.FieldCategory, field.TypeString, value)
	}
	if value, ok := ntuo.mutation.IsActive(); ok {
		_spec.SetField(notificationtype.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := ntuo.mutation.DefaultEnabled(); ok {
		_spec.SetField(notificationtype.FieldDefaultEnabled, field.TypeBool, value)
	}
	if value, ok := ntuo.mutation.SupportedChannels(); ok {
		_spec.SetField(notificationtype.FieldSupportedChannels, field.TypeJSON, value)
	}
	if value, ok := ntuo.mutation.AppendedSupportedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationtype.FieldSupportedChannels, value)
		})
	}
	if ntuo.mutation.SupportedChannelsCleared() {
		_spec.ClearField(notificationtype.FieldSupportedChannels, field.TypeJSON)
	}
	if ntuo.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ntuo.mutation.RemovedUserConfigsIDs(); len(nodes) > 0 && !ntuo.mutation.UserConfigsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ntuo.mutation.UserConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationtype.UserConfigsTable,
			Columns: []string{notificationtype.UserConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ntuo.modifiers...)
	_node = &NotificationType{config: ntuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ntuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ntuo.mutation.done = true
	return _node, nil
}
