// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/subscriber"
)

// SubscriberUpdate is the builder for updating Subscriber entities.
type SubscriberUpdate struct {
	config
	hooks     []Hook
	mutation  *SubscriberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SubscriberUpdate builder.
func (su *SubscriberUpdate) Where(ps ...predicate.Subscriber) *SubscriberUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetEmail sets the "email" field.
func (su *SubscriberUpdate) SetEmail(s string) *SubscriberUpdate {
	su.mutation.SetEmail(s)
	return su
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (su *SubscriberUpdate) SetNillableEmail(s *string) *SubscriberUpdate {
	if s != nil {
		su.SetEmail(*s)
	}
	return su
}

// SetIsActive sets the "is_active" field.
func (su *SubscriberUpdate) SetIsActive(b bool) *SubscriberUpdate {
	su.mutation.SetIsActive(b)
	return su
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (su *SubscriberUpdate) SetNillableIsActive(b *bool) *SubscriberUpdate {
	if b != nil {
		su.SetIsActive(*b)
	}
	return su
}

// SetToken sets the "token" field.
func (su *SubscriberUpdate) SetToken(s string) *SubscriberUpdate {
	su.mutation.SetToken(s)
	return su
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (su *SubscriberUpdate) SetNillableToken(s *string) *SubscriberUpdate {
	if s != nil {
		su.SetToken(*s)
	}
	return su
}

// ClearToken clears the value of the "token" field.
func (su *SubscriberUpdate) ClearToken() *SubscriberUpdate {
	su.mutation.ClearToken()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SubscriberUpdate) SetUpdatedAt(t time.Time) *SubscriberUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the SubscriberMutation object of the builder.
func (su *SubscriberUpdate) Mutation() *SubscriberMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SubscriberUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubscriberUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubscriberUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubscriberUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SubscriberUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := subscriber.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SubscriberUpdate) check() error {
	if v, ok := su.mutation.Email(); ok {
		if err := subscriber.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Subscriber.email": %w`, err)}
		}
	}
	if v, ok := su.mutation.Token(); ok {
		if err := subscriber.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Subscriber.token": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (su *SubscriberUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubscriberUpdate {
	su.modifiers = append(su.modifiers, modifiers...)
	return su
}

func (su *SubscriberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriber.Table, subscriber.Columns, sqlgraph.NewFieldSpec(subscriber.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Email(); ok {
		_spec.SetField(subscriber.FieldEmail, field.TypeString, value)
	}
	if value, ok := su.mutation.IsActive(); ok {
		_spec.SetField(subscriber.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := su.mutation.Token(); ok {
		_spec.SetField(subscriber.FieldToken, field.TypeString, value)
	}
	if su.mutation.TokenCleared() {
		_spec.ClearField(subscriber.FieldToken, field.TypeString)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriber.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(su.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriber.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SubscriberUpdateOne is the builder for updating a single Subscriber entity.
type SubscriberUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SubscriberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetEmail sets the "email" field.
func (suo *SubscriberUpdateOne) SetEmail(s string) *SubscriberUpdateOne {
	suo.mutation.SetEmail(s)
	return suo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suo *SubscriberUpdateOne) SetNillableEmail(s *string) *SubscriberUpdateOne {
	if s != nil {
		suo.SetEmail(*s)
	}
	return suo
}

// SetIsActive sets the "is_active" field.
func (suo *SubscriberUpdateOne) SetIsActive(b bool) *SubscriberUpdateOne {
	suo.mutation.SetIsActive(b)
	return suo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (suo *SubscriberUpdateOne) SetNillableIsActive(b *bool) *SubscriberUpdateOne {
	if b != nil {
		suo.SetIsActive(*b)
	}
	return suo
}

// SetToken sets the "token" field.
func (suo *SubscriberUpdateOne) SetToken(s string) *SubscriberUpdateOne {
	suo.mutation.SetToken(s)
	return suo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (suo *SubscriberUpdateOne) SetNillableToken(s *string) *SubscriberUpdateOne {
	if s != nil {
		suo.SetToken(*s)
	}
	return suo
}

// ClearToken clears the value of the "token" field.
func (suo *SubscriberUpdateOne) ClearToken() *SubscriberUpdateOne {
	suo.mutation.ClearToken()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SubscriberUpdateOne) SetUpdatedAt(t time.Time) *SubscriberUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the SubscriberMutation object of the builder.
func (suo *SubscriberUpdateOne) Mutation() *SubscriberMutation {
	return suo.mutation
}

// Where appends a list predicates to the SubscriberUpdate builder.
func (suo *SubscriberUpdateOne) Where(ps ...predicate.Subscriber) *SubscriberUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SubscriberUpdateOne) Select(field string, fields ...string) *SubscriberUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Subscriber entity.
func (suo *SubscriberUpdateOne) Save(ctx context.Context) (*Subscriber, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubscriberUpdateOne) SaveX(ctx context.Context) *Subscriber {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SubscriberUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubscriberUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SubscriberUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := subscriber.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SubscriberUpdateOne) check() error {
	if v, ok := suo.mutation.Email(); ok {
		if err := subscriber.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Subscriber.email": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Token(); ok {
		if err := subscriber.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Subscriber.token": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (suo *SubscriberUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubscriberUpdateOne {
	suo.modifiers = append(suo.modifiers, modifiers...)
	return suo
}

func (suo *SubscriberUpdateOne) sqlSave(ctx context.Context) (_node *Subscriber, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriber.Table, subscriber.Columns, sqlgraph.NewFieldSpec(subscriber.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscriber.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriber.FieldID)
		for _, f := range fields {
			if !subscriber.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriber.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Email(); ok {
		_spec.SetField(subscriber.FieldEmail, field.TypeString, value)
	}
	if value, ok := suo.mutation.IsActive(); ok {
		_spec.SetField(subscriber.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Token(); ok {
		_spec.SetField(subscriber.FieldToken, field.TypeString, value)
	}
	if suo.mutation.TokenCleared() {
		_spec.ClearField(subscriber.FieldToken, field.TypeString)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriber.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(suo.modifiers...)
	_node = &Subscriber{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriber.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
