// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/notificationtype"
	"github.com/anzhiyu-c/anheyu-app/ent/user"
	"github.com/anzhiyu-c/anheyu-app/ent/usernotificationconfig"
)

// UserNotificationConfigCreate is the builder for creating a UserNotificationConfig entity.
type UserNotificationConfigCreate struct {
	config
	mutation *UserNotificationConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (uncc *UserNotificationConfigCreate) SetCreatedAt(t time.Time) *UserNotificationConfigCreate {
	uncc.mutation.SetCreatedAt(t)
	return uncc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uncc *UserNotificationConfigCreate) SetNillableCreatedAt(t *time.Time) *UserNotificationConfigCreate {
	if t != nil {
		uncc.SetCreatedAt(*t)
	}
	return uncc
}

// SetUpdatedAt sets the "updated_at" field.
func (uncc *UserNotificationConfigCreate) SetUpdatedAt(t time.Time) *UserNotificationConfigCreate {
	uncc.mutation.SetUpdatedAt(t)
	return uncc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uncc *UserNotificationConfigCreate) SetNillableUpdatedAt(t *time.Time) *UserNotificationConfigCreate {
	if t != nil {
		uncc.SetUpdatedAt(*t)
	}
	return uncc
}

// SetUserID sets the "user_id" field.
func (uncc *UserNotificationConfigCreate) SetUserID(u uint) *UserNotificationConfigCreate {
	uncc.mutation.SetUserID(u)
	return uncc
}

// SetNotificationTypeID sets the "notification_type_id" field.
func (uncc *UserNotificationConfigCreate) SetNotificationTypeID(u uint) *UserNotificationConfigCreate {
	uncc.mutation.SetNotificationTypeID(u)
	return uncc
}

// SetIsEnabled sets the "is_enabled" field.
func (uncc *UserNotificationConfigCreate) SetIsEnabled(b bool) *UserNotificationConfigCreate {
	uncc.mutation.SetIsEnabled(b)
	return uncc
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (uncc *UserNotificationConfigCreate) SetNillableIsEnabled(b *bool) *UserNotificationConfigCreate {
	if b != nil {
		uncc.SetIsEnabled(*b)
	}
	return uncc
}

// SetEnabledChannels sets the "enabled_channels" field.
func (uncc *UserNotificationConfigCreate) SetEnabledChannels(s []string) *UserNotificationConfigCreate {
	uncc.mutation.SetEnabledChannels(s)
	return uncc
}

// SetNotificationEmail sets the "notification_email" field.
func (uncc *UserNotificationConfigCreate) SetNotificationEmail(s string) *UserNotificationConfigCreate {
	uncc.mutation.SetNotificationEmail(s)
	return uncc
}

// SetNillableNotificationEmail sets the "notification_email" field if the given value is not nil.
func (uncc *UserNotificationConfigCreate) SetNillableNotificationEmail(s *string) *UserNotificationConfigCreate {
	if s != nil {
		uncc.SetNotificationEmail(*s)
	}
	return uncc
}

// SetCustomSettings sets the "custom_settings" field.
func (uncc *UserNotificationConfigCreate) SetCustomSettings(m map[string]interface{}) *UserNotificationConfigCreate {
	uncc.mutation.SetCustomSettings(m)
	return uncc
}

// SetID sets the "id" field.
func (uncc *UserNotificationConfigCreate) SetID(u uint) *UserNotificationConfigCreate {
	uncc.mutation.SetID(u)
	return uncc
}

// SetUser sets the "user" edge to the User entity.
func (uncc *UserNotificationConfigCreate) SetUser(u *User) *UserNotificationConfigCreate {
	return uncc.SetUserID(u.ID)
}

// SetNotificationType sets the "notification_type" edge to the NotificationType entity.
func (uncc *UserNotificationConfigCreate) SetNotificationType(n *NotificationType) *UserNotificationConfigCreate {
	return uncc.SetNotificationTypeID(n.ID)
}

// Mutation returns the UserNotificationConfigMutation object of the builder.
func (uncc *UserNotificationConfigCreate) Mutation() *UserNotificationConfigMutation {
	return uncc.mutation
}

// Save creates the UserNotificationConfig in the database.
func (uncc *UserNotificationConfigCreate) Save(ctx context.Context) (*UserNotificationConfig, error) {
	uncc.defaults()
	return withHooks(ctx, uncc.sqlSave, uncc.mutation, uncc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uncc *UserNotificationConfigCreate) SaveX(ctx context.Context) *UserNotificationConfig {
	v, err := uncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uncc *UserNotificationConfigCreate) Exec(ctx context.Context) error {
	_, err := uncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uncc *UserNotificationConfigCreate) ExecX(ctx context.Context) {
	if err := uncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uncc *UserNotificationConfigCreate) defaults() {
	if _, ok := uncc.mutation.CreatedAt(); !ok {
		v := usernotificationconfig.DefaultCreatedAt()
		uncc.mutation.SetCreatedAt(v)
	}
	if _, ok := uncc.mutation.UpdatedAt(); !ok {
		v := usernotificationconfig.DefaultUpdatedAt()
		uncc.mutation.SetUpdatedAt(v)
	}
	if _, ok := uncc.mutation.IsEnabled(); !ok {
		v := usernotificationconfig.DefaultIsEnabled
		uncc.mutation.SetIsEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uncc *UserNotificationConfigCreate) check() error {
	if _, ok := uncc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserNotificationConfig.created_at"`)}
	}
	if _, ok := uncc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserNotificationConfig.updated_at"`)}
	}
	if _, ok := uncc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserNotificationConfig.user_id"`)}
	}
	if _, ok := uncc.mutation.NotificationTypeID(); !ok {
		return &ValidationError{Name: "notification_type_id", err: errors.New(`ent: missing required field "UserNotificationConfig.notification_type_id"`)}
	}
	if _, ok := uncc.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "UserNotificationConfig.is_enabled"`)}
	}
	if v, ok := uncc.mutation.NotificationEmail(); ok {
		if err := usernotificationconfig.NotificationEmailValidator(v); err != nil {
			return &ValidationError{Name: "notification_email", err: fmt.Errorf(`ent: validator failed for field "UserNotificationConfig.notification_email": %w`, err)}
		}
	}
	if len(uncc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserNotificationConfig.user"`)}
	}
	if len(uncc.mutation.NotificationTypeIDs()) == 0 {
		return &ValidationError{Name: "notification_type", err: errors.New(`ent: missing required edge "UserNotificationConfig.notification_type"`)}
	}
	return nil
}

func (uncc *UserNotificationConfigCreate) sqlSave(ctx context.Context) (*UserNotificationConfig, error) {
	if err := uncc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	uncc.mutation.id = &_node.ID
	uncc.mutation.done = true
	return _node, nil
}

func (uncc *UserNotificationConfigCreate) createSpec() (*UserNotificationConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &UserNotificationConfig{config: uncc.config}
		_spec = sqlgraph.NewCreateSpec(usernotificationconfig.Table, sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint))
	)
	_spec.OnConflict = uncc.conflict
	if id, ok := uncc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uncc.mutation.CreatedAt(); ok {
		_spec.SetField(usernotificationconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uncc.mutation.UpdatedAt(); ok {
		_spec.SetField(usernotificationconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := uncc.mutation.IsEnabled(); ok {
		_spec.SetField(usernotificationconfig.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := uncc.mutation.EnabledChannels(); ok {
		_spec.SetField(usernotificationconfig.FieldEnabledChannels, field.TypeJSON, value)
		_node.EnabledChannels = value
	}
	if value, ok := uncc.mutation.NotificationEmail(); ok {
		_spec.SetField(usernotificationconfig.FieldNotificationEmail, field.TypeString, value)
		_node.NotificationEmail = value
	}
	if value, ok := uncc.mutation.CustomSettings(); ok {
		_spec.SetField(usernotificationconfig.FieldCustomSettings, field.TypeJSON, value)
		_node.CustomSettings = value
	}
	if nodes := uncc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usernotificationconfig.UserTable,
			Columns: []string{usernotificationconfig.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uncc.mutation.NotificationTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usernotificationconfig.NotificationTypeTable,
			Columns: []string{usernotificationconfig.NotificationTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationtype.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserNotificationConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserNotificationConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (uncc *UserNotificationConfigCreate) OnConflict(opts ...sql.ConflictOption) *UserNotificationConfigUpsertOne {
	uncc.conflict = opts
	return &UserNotificationConfigUpsertOne{
		create: uncc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uncc *UserNotificationConfigCreate) OnConflictColumns(columns ...string) *UserNotificationConfigUpsertOne {
	uncc.conflict = append(uncc.conflict, sql.ConflictColumns(columns...))
	return &UserNotificationConfigUpsertOne{
		create: uncc,
	}
}

type (
	// UserNotificationConfigUpsertOne is the builder for "upsert"-ing
	//  one UserNotificationConfig node.
	UserNotificationConfigUpsertOne struct {
		create *UserNotificationConfigCreate
	}

	// UserNotificationConfigUpsert is the "OnConflict" setter.
	UserNotificationConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserNotificationConfigUpsert) SetUpdatedAt(v time.Time) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateUpdatedAt() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserNotificationConfigUpsert) SetUserID(v uint) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateUserID() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldUserID)
	return u
}

// SetNotificationTypeID sets the "notification_type_id" field.
func (u *UserNotificationConfigUpsert) SetNotificationTypeID(v uint) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldNotificationTypeID, v)
	return u
}

// UpdateNotificationTypeID sets the "notification_type_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateNotificationTypeID() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldNotificationTypeID)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UserNotificationConfigUpsert) SetIsEnabled(v bool) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateIsEnabled() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldIsEnabled)
	return u
}

// SetEnabledChannels sets the "enabled_channels" field.
func (u *UserNotificationConfigUpsert) SetEnabledChannels(v []string) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldEnabledChannels, v)
	return u
}

// UpdateEnabledChannels sets the "enabled_channels" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateEnabledChannels() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldEnabledChannels)
	return u
}

// ClearEnabledChannels clears the value of the "enabled_channels" field.
func (u *UserNotificationConfigUpsert) ClearEnabledChannels() *UserNotificationConfigUpsert {
	u.SetNull(usernotificationconfig.FieldEnabledChannels)
	return u
}

// SetNotificationEmail sets the "notification_email" field.
func (u *UserNotificationConfigUpsert) SetNotificationEmail(v string) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldNotificationEmail, v)
	return u
}

// UpdateNotificationEmail sets the "notification_email" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateNotificationEmail() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldNotificationEmail)
	return u
}

// ClearNotificationEmail clears the value of the "notification_email" field.
func (u *UserNotificationConfigUpsert) ClearNotificationEmail() *UserNotificationConfigUpsert {
	u.SetNull(usernotificationconfig.FieldNotificationEmail)
	return u
}

// SetCustomSettings sets the "custom_settings" field.
func (u *UserNotificationConfigUpsert) SetCustomSettings(v map[string]interface{}) *UserNotificationConfigUpsert {
	u.Set(usernotificationconfig.FieldCustomSettings, v)
	return u
}

// UpdateCustomSettings sets the "custom_settings" field to the value that was provided on create.
func (u *UserNotificationConfigUpsert) UpdateCustomSettings() *UserNotificationConfigUpsert {
	u.SetExcluded(usernotificationconfig.FieldCustomSettings)
	return u
}

// ClearCustomSettings clears the value of the "custom_settings" field.
func (u *UserNotificationConfigUpsert) ClearCustomSettings() *UserNotificationConfigUpsert {
	u.SetNull(usernotificationconfig.FieldCustomSettings)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usernotificationconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserNotificationConfigUpsertOne) UpdateNewValues() *UserNotificationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(usernotificationconfig.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usernotificationconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserNotificationConfigUpsertOne) Ignore() *UserNotificationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserNotificationConfigUpsertOne) DoNothing() *UserNotificationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserNotificationConfigCreate.OnConflict
// documentation for more info.
func (u *UserNotificationConfigUpsertOne) Update(set func(*UserNotificationConfigUpsert)) *UserNotificationConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserNotificationConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserNotificationConfigUpsertOne) SetUpdatedAt(v time.Time) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateUpdatedAt() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserNotificationConfigUpsertOne) SetUserID(v uint) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateUserID() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetNotificationTypeID sets the "notification_type_id" field.
func (u *UserNotificationConfigUpsertOne) SetNotificationTypeID(v uint) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetNotificationTypeID(v)
	})
}

// UpdateNotificationTypeID sets the "notification_type_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateNotificationTypeID() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateNotificationTypeID()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UserNotificationConfigUpsertOne) SetIsEnabled(v bool) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateIsEnabled() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetEnabledChannels sets the "enabled_channels" field.
func (u *UserNotificationConfigUpsertOne) SetEnabledChannels(v []string) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetEnabledChannels(v)
	})
}

// UpdateEnabledChannels sets the "enabled_channels" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateEnabledChannels() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateEnabledChannels()
	})
}

// ClearEnabledChannels clears the value of the "enabled_channels" field.
func (u *UserNotificationConfigUpsertOne) ClearEnabledChannels() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearEnabledChannels()
	})
}

// SetNotificationEmail sets the "notification_email" field.
func (u *UserNotificationConfigUpsertOne) SetNotificationEmail(v string) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetNotificationEmail(v)
	})
}

// UpdateNotificationEmail sets the "notification_email" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateNotificationEmail() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateNotificationEmail()
	})
}

// ClearNotificationEmail clears the value of the "notification_email" field.
func (u *UserNotificationConfigUpsertOne) ClearNotificationEmail() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearNotificationEmail()
	})
}

// SetCustomSettings sets the "custom_settings" field.
func (u *UserNotificationConfigUpsertOne) SetCustomSettings(v map[string]interface{}) *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetCustomSettings(v)
	})
}

// UpdateCustomSettings sets the "custom_settings" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertOne) UpdateCustomSettings() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateCustomSettings()
	})
}

// ClearCustomSettings clears the value of the "custom_settings" field.
func (u *UserNotificationConfigUpsertOne) ClearCustomSettings() *UserNotificationConfigUpsertOne {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearCustomSettings()
	})
}

// Exec executes the query.
func (u *UserNotificationConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserNotificationConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserNotificationConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserNotificationConfigUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserNotificationConfigUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserNotificationConfigCreateBulk is the builder for creating many UserNotificationConfig entities in bulk.
type UserNotificationConfigCreateBulk struct {
	config
	err      error
	builders []*UserNotificationConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the UserNotificationConfig entities in the database.
func (unccb *UserNotificationConfigCreateBulk) Save(ctx context.Context) ([]*UserNotificationConfig, error) {
	if unccb.err != nil {
		return nil, unccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(unccb.builders))
	nodes := make([]*UserNotificationConfig, len(unccb.builders))
	mutators := make([]Mutator, len(unccb.builders))
	for i := range unccb.builders {
		func(i int, root context.Context) {
			builder := unccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserNotificationConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, unccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = unccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, unccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, unccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (unccb *UserNotificationConfigCreateBulk) SaveX(ctx context.Context) []*UserNotificationConfig {
	v, err := unccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (unccb *UserNotificationConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := unccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (unccb *UserNotificationConfigCreateBulk) ExecX(ctx context.Context) {
	if err := unccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserNotificationConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserNotificationConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (unccb *UserNotificationConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserNotificationConfigUpsertBulk {
	unccb.conflict = opts
	return &UserNotificationConfigUpsertBulk{
		create: unccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (unccb *UserNotificationConfigCreateBulk) OnConflictColumns(columns ...string) *UserNotificationConfigUpsertBulk {
	unccb.conflict = append(unccb.conflict, sql.ConflictColumns(columns...))
	return &UserNotificationConfigUpsertBulk{
		create: unccb,
	}
}

// UserNotificationConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of UserNotificationConfig nodes.
type UserNotificationConfigUpsertBulk struct {
	create *UserNotificationConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usernotificationconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserNotificationConfigUpsertBulk) UpdateNewValues() *UserNotificationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(usernotificationconfig.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usernotificationconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserNotificationConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserNotificationConfigUpsertBulk) Ignore() *UserNotificationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserNotificationConfigUpsertBulk) DoNothing() *UserNotificationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserNotificationConfigCreateBulk.OnConflict
// documentation for more info.
func (u *UserNotificationConfigUpsertBulk) Update(set func(*UserNotificationConfigUpsert)) *UserNotificationConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserNotificationConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserNotificationConfigUpsertBulk) SetUpdatedAt(v time.Time) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateUpdatedAt() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserNotificationConfigUpsertBulk) SetUserID(v uint) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateUserID() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetNotificationTypeID sets the "notification_type_id" field.
func (u *UserNotificationConfigUpsertBulk) SetNotificationTypeID(v uint) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetNotificationTypeID(v)
	})
}

// UpdateNotificationTypeID sets the "notification_type_id" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateNotificationTypeID() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateNotificationTypeID()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UserNotificationConfigUpsertBulk) SetIsEnabled(v bool) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateIsEnabled() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetEnabledChannels sets the "enabled_channels" field.
func (u *UserNotificationConfigUpsertBulk) SetEnabledChannels(v []string) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetEnabledChannels(v)
	})
}

// UpdateEnabledChannels sets the "enabled_channels" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateEnabledChannels() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateEnabledChannels()
	})
}

// ClearEnabledChannels clears the value of the "enabled_channels" field.
func (u *UserNotificationConfigUpsertBulk) ClearEnabledChannels() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearEnabledChannels()
	})
}

// SetNotificationEmail sets the "notification_email" field.
func (u *UserNotificationConfigUpsertBulk) SetNotificationEmail(v string) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetNotificationEmail(v)
	})
}

// UpdateNotificationEmail sets the "notification_email" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateNotificationEmail() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateNotificationEmail()
	})
}

// ClearNotificationEmail clears the value of the "notification_email" field.
func (u *UserNotificationConfigUpsertBulk) ClearNotificationEmail() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearNotificationEmail()
	})
}

// SetCustomSettings sets the "custom_settings" field.
func (u *UserNotificationConfigUpsertBulk) SetCustomSettings(v map[string]interface{}) *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.SetCustomSettings(v)
	})
}

// UpdateCustomSettings sets the "custom_settings" field to the value that was provided on create.
func (u *UserNotificationConfigUpsertBulk) UpdateCustomSettings() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.UpdateCustomSettings()
	})
}

// ClearCustomSettings clears the value of the "custom_settings" field.
func (u *UserNotificationConfigUpsertBulk) ClearCustomSettings() *UserNotificationConfigUpsertBulk {
	return u.Update(func(s *UserNotificationConfigUpsert) {
		s.ClearCustomSettings()
	})
}

// Exec executes the query.
func (u *UserNotificationConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserNotificationConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserNotificationConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserNotificationConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
