// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/usernotificationconfig"
)

// UserNotificationConfigDelete is the builder for deleting a UserNotificationConfig entity.
type UserNotificationConfigDelete struct {
	config
	hooks    []Hook
	mutation *UserNotificationConfigMutation
}

// Where appends a list predicates to the UserNotificationConfigDelete builder.
func (uncd *UserNotificationConfigDelete) Where(ps ...predicate.UserNotificationConfig) *UserNotificationConfigDelete {
	uncd.mutation.Where(ps...)
	return uncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uncd *UserNotificationConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uncd.sqlExec, uncd.mutation, uncd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uncd *UserNotificationConfigDelete) ExecX(ctx context.Context) int {
	n, err := uncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uncd *UserNotificationConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usernotificationconfig.Table, sqlgraph.NewFieldSpec(usernotificationconfig.FieldID, field.TypeUint))
	if ps := uncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uncd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uncd.mutation.done = true
	return affected, err
}

// UserNotificationConfigDeleteOne is the builder for deleting a single UserNotificationConfig entity.
type UserNotificationConfigDeleteOne struct {
	uncd *UserNotificationConfigDelete
}

// Where appends a list predicates to the UserNotificationConfigDelete builder.
func (uncdo *UserNotificationConfigDeleteOne) Where(ps ...predicate.UserNotificationConfig) *UserNotificationConfigDeleteOne {
	uncdo.uncd.mutation.Where(ps...)
	return uncdo
}

// Exec executes the deletion query.
func (uncdo *UserNotificationConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := uncdo.uncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usernotificationconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uncdo *UserNotificationConfigDeleteOne) ExecX(ctx context.Context) {
	if err := uncdo.Exec(ctx); err != nil {
		panic(err)
	}
}
