// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anzhiyu-c/anheyu-app/ent/predicate"
	"github.com/anzhiyu-c/anheyu-app/ent/visitorlog"
)

// VisitorLogDelete is the builder for deleting a VisitorLog entity.
type VisitorLogDelete struct {
	config
	hooks    []Hook
	mutation *VisitorLogMutation
}

// Where appends a list predicates to the VisitorLogDelete builder.
func (vld *VisitorLogDelete) Where(ps ...predicate.VisitorLog) *VisitorLogDelete {
	vld.mutation.Where(ps...)
	return vld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vld *VisitorLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vld.sqlExec, vld.mutation, vld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vld *VisitorLogDelete) ExecX(ctx context.Context) int {
	n, err := vld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vld *VisitorLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(visitorlog.Table, sqlgraph.NewFieldSpec(visitorlog.FieldID, field.TypeUint))
	if ps := vld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vld.mutation.done = true
	return affected, err
}

// VisitorLogDeleteOne is the builder for deleting a single VisitorLog entity.
type VisitorLogDeleteOne struct {
	vld *VisitorLogDelete
}

// Where appends a list predicates to the VisitorLogDelete builder.
func (vldo *VisitorLogDeleteOne) Where(ps ...predicate.VisitorLog) *VisitorLogDeleteOne {
	vldo.vld.mutation.Where(ps...)
	return vldo
}

// Exec executes the deletion query.
func (vldo *VisitorLogDeleteOne) Exec(ctx context.Context) error {
	n, err := vldo.vld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{visitorlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vldo *VisitorLogDeleteOne) ExecX(ctx context.Context) {
	if err := vldo.Exec(ctx); err != nil {
		panic(err)
	}
}
